# Arhmetic Operations with Numpy Arrays

In [4]:
import numpy as np

In [5]:
d = np.array([4,8,7,9])

In [6]:
d*2

array([ 8, 16, 14, 18])

In [7]:
# The Arthmetic operations is possible in Numpy array but is doesnot work in Python list lets try this
list1 = [4,8,7,9]
list1*2
It doesnot multiply the elemensts but repeat elemennts

[4, 8, 7, 9, 4, 8, 7, 9]

In [8]:
d/2

array([2. , 4. , 3.5, 4.5])

In [11]:
d/2

array([2. , 4. , 3.5, 4.5])