# Arhmetic Operations with Numpy Arrays

In [1]:
import numpy as np

In [ ]:
d = np.array([4,8,7,9])

In [ ]:
d*2

In [ ]:
# The Arthmetic operations is possible in Numpy array but is doesnot work in Python list lets try this
list1 = [4,8,7,9]
list1*2
It doesnot multiply the elemensts but repeat elemennts

In [ ]:
d/2

In [ ]:
d/2

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3
