# Reshape Array in Numpy

what Does Reshape means?

reshape means you reshape the 1D array in to 2D or change rows and Columns

For reshaping it is compulsory to store the reshape dimentions into a variable Otherwise it doesnot change the dimention

In [21]:
import numpy as np

# We write an array

a = np.array([[1 ,2, 3, 4 ,5], [6 , 7 , 8 , 9 , 10]])
print(a.shape) #Find the shape of the array ( rows ,columns)
# now we reshape 2 x 5 in to multiple ways
a = a.reshape(5,2) # 5 rows and 2 columns
print(a)


(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [39]:
x = np.zeros((2,6))
print(x)# An array of zeros with 2 rows and 6 columns

print("\nShape of array: ")

print(x.shape)
print("\nReshape: 1 row 12 columns")
y = x.reshape(1, 12)
print(y)


print("\nReshape: 6 row 2 columns")
y = x.reshape(6, 2)
print(y)


print("\nReshape: A 3D Array of 2 plains , 3 rows and 12 columns")
y = x.reshape(2,3,2)
print(y)


print("\nReshape: 3 Plains 2 rows 2 columns")
y = x.reshape(3,2,2)
print(y)


print("\nReshape: 2 Plains 2 rows 3 columns")
y = x.reshape(2,2,3)
print(y)


print("\nReshape: 4 Plains 1 rows 3 columns")
y = x.reshape(4,1,3)
print(y)

print("\nReshape: 6 Plains 1 rows 2 columns")
y = x.reshape(6,1,2)
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Shape of array: 
(2, 6)

Reshape: 1 row 12 columns
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Reshape: 6 row 2 columns
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Reshape: A 3D Array of 2 plains , 3 rows and 12 columns
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

Reshape: 3 Plains 2 rows 2 columns
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

Reshape: 2 Plains 2 rows 3 columns
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

Reshape: 4 Plains 1 rows 3 columns
[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]

Reshape: 6 Plains 1 rows 2 columns
[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]]


# Neagative Values in Reshape


It simply Ignores the negative value

In [44]:
x = np.zeros((2,6))
print(x)

y = x.reshape(1, -12) #It ignores the Negative sign and print matrix 1 row 1 columns
print(y)

y = x.reshape(3,2,-2) #It ignores the Negative sign and print matrix 3 plains 2 row 2 columns
print(y)





[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
